#!/usr/bin/env python
import pandas as pd
import numpy as np

try:
    df = pd.read_hdf("localbitcoins.h5", "trades")
except IOError:
    df = pd.read_json("https://localbitcoins.com/bitcoincharts/NGN/trades.json")

while True:
    tid = df.tid.max()
    df_u = pd.read_json("https://localbitcoins.com/bitcoincharts/NGN/trades.json?since={}".format(tid))
    if df_u.empty:
        break
    df = df.append(df_u)

df.reset_index(drop=True, inplace=True)
df.index = df.date
df.to_hdf("localbitcoins.h5", "trades", mode="w")

df['volume'] = df.amount * df.price
df['trades'] = np.array([1] * len(df))
df[['volume', 'trades']].round(2).resample('1w-sat').sum().fillna(0).to_csv('localbitcoins-ngn.csv')
